name: cse5243-proj
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cudatoolkit=10.1.243
  - freetype=2.9.1
  - intel-openmp=2020.0
  - jpeg=9b
  - libffi=3.2.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ninja=1.9.0
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1f
  - pillow=7.0.0
  - pip=20.0.2
  - python=3.6.10
  - pytorch=1.4.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision=0.5.0
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.4
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - idna==2.9
    - importlib-metadata==1.6.0
    - ipykernel==5.2.1
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.0
    - jinja2==2.11.2
    - joblib==0.14.1
    - json5==0.9.4
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - jupyterlab==2.1.0
    - jupyterlab-server==1.1.1
    - kiwisolver==1.2.0
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.5
    - notebook==6.0.3
    - numpy==1.18.2
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pexpect==4.8.0
    - libstdcxx-ng==9.1.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyzmq==19.0.0
    - qtconsole==4.7.3
    - qtpy==1.9.0
    - libedit==3.1.20181209
    - requests==2.23.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - libgfortran-ng==7.3.0
    - readline==8.0
    - send2trash==1.5.0
    - terminado==0.8.3
    - testpath==0.4.4
    - libgcc-ng==9.1.0
    - tornado==6.0.4
    - ncurses==6.2
    - ld_impl_linux-64==2.33.1
    - tqdm==4.45.0
    - traitlets==4.3.3
    - urllib3==1.25.9
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.1.0

